-- Seed initial data for Nature Medics Ayurveda / Suwayu Ayurveda

INSERT INTO treatments (name, slug, category, description, duration_minutes, price, currency, image_url, is_active) VALUES
('Panchakarma Full Detoxification', 'panchakarma-detox', 'Detoxification', 'A comprehensive 5-fold Ayurvedic detoxification procedure designed to purify body tissues, balance the three doshas (Vata, Pitta, Kapha), and eliminate deep-seated toxins.', 120, 15000.00, 'LKR', 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=800', TRUE),
('Shirodhara Mind & Stress Relief Therapy', 'shirodhara-therapy', 'Rejuvenation', 'A continuous, gentle stream of warm medicated herbal oil poured over the forehead (third eye). Relieves stress, insomnia, anxiety, and enhances mental clarity.', 60, 8500.00, 'LKR', 'https://images.unsplash.com/photo-1519823551278-64ac92734fb1?auto=format&fit=crop&q=80&w=800', TRUE),
('Abhyanga Full Body Herbal Massage', 'abhyanga-massage', 'Massage Therapy', 'Traditional full-body rhythmic massage using custom-selected herbal oils. Improves blood circulation, eases joint stiffness, and rejuvenates skin tone.', 90, 9500.00, 'LKR', 'https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&q=80&w=800', TRUE),
('Kizhi Herbal Steam & Bolus Therapy', 'kizhi-herbal-therapy', 'Pain Management', 'Application of warm poultices filled with ground herbs and oils. Targeted treatment for arthritis, muscular aches, chronic back pain, and joint inflammation.', 60, 7500.00, 'LKR', 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&q=80&w=800', TRUE),
('Ayurvedic Pulse Diagnosis & Doctor Consultation', 'ayurvedic-consultation', 'Consultation', 'In-depth consultation with our certified Ayurvedic physician (Nadi Pariksha / Pulse Reading) to assess dosha constitution and provide custom herbal prescriptions.', 45, 3500.00, 'LKR', 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&q=80&w=800', TRUE),
('Mukha Lepanam Herbal Facial & Skin Care', 'mukha-lepanam-facial', 'Beauty & Wellness', 'Natural facial treatment using organic herbal pastes, exotic flower extracts, and sandalwood oils to restore natural radiance and glow to skin.', 60, 6500.00, 'LKR', 'https://images.unsplash.com/photo-1512290900673-2067406a6b82?auto=format&fit=crop&q=80&w=800', TRUE)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO products (name, slug, category, description, price, currency, stock_quantity, image_url, is_available) VALUES
('Nature Medics Herbal Rejuvenation Oil', 'rejuvenation-oil', 'Oils', 'Authentic Siddha medicated oil prepared with rare mountain herbs to nourish hair, scalp, and skin.', 2400.00, 'LKR', 50, 'https://images.unsplash.com/photo-1608248597263-00079e96048a?auto=format&fit=crop&q=80&w=800', TRUE),
('Pure Organic Triphala Powder (200g)', 'triphala-powder', 'Herbal Powders', 'Traditional blend of Haritaki, Bibhitaki, and Amalaki for digestive wellness and body cleansing.', 1800.00, 'LKR', 100, 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&q=80&w=800', TRUE),
('Ayurvedic Immunity Arishta', 'immunity-arishta', 'Elixirs', 'Fermented herbal tonic formulated to enhance vital energy (Ojas) and natural immunity.', 3200.00, 'LKR', 35, 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800', TRUE)
ON CONFLICT (slug) DO NOTHING;
